application:
  name: my-application
  project: getting-started-project
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- type: mysql
  version: "8.0"
  name: mysql-db
routers:
- name: main
  routes:
  - application_name: my-application
    paths:
    - /
